name: CI & Deploy (Render)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Trigger Render deploy (Frontend Static Site)
        env:
          HOOK: ${{ secrets.RENDER_STATIC_HOOK_URL }}
        run: |
          curl -fsSL -X POST "$HOOK"

  backend:
    runs-on: ubuntu-latest
    needs: frontend
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Trigger Render deploy (Backend Docker Service)
        env:
          HOOK: ${{ secrets.RENDER_BACKEND_HOOK_URL }}
        run: |
          curl -fsSL -X POST "$HOOK"
